name: Smoke Test

on:
  workflow_dispatch:
  pull_request: # TODO Temporary, but maybe we might keep it

jobs:
  test:
    name: ${{ matrix.driver.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: BrowserKit (http client)
            driverRepoUrl: https://github.com/minkphp/MinkBrowserKitDriver.git
            php: 7.2
            testCmd: ./vendor/bin/phpunit --colors=always --testdox --configuration ./phpunit.http_client.xml

          - name: BrowserKit (http kernel)
            driverRepoUrl: https://github.com/minkphp/MinkBrowserKitDriver.git
            php: 7.2
            testCmd: ./vendor/bin/phpunit --colors=always --testdox

          - name: Chrome
            driverRepoUrl: https://gitlab.com/behat-chrome/chrome-mink-driver.git
            php: 7.4
            setUpCmd: |
              docker run --detach --quiet --net host --volume /dev/shm:/dev/shm --shm-size 2g --volume ./vendor/mink/driver-testsuite/web-fixtures:/fixtures \
                         --name chrome zenika/alpine-chrome:latest \
                         "--remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --disable-gpu --headless=new --disable-extensions --no-sandbox --use-gl=swiftshader --disable-software-rasterizer --disable-dev-shm-usage"
              sed "s#http://localhost/#http://localhost:8002/#" phpunit.xml.dist > phpunit.xml
              while ! nc -z localhost 9222 </dev/null; do echo Waiting for chrome to start...; sleep 1; done
            testCmd: |
              export WEB_FIXTURES_BROWSER=chrome
              export DRIVER_MACHINE_BASE_PATH=/fixtures/
              ./vendor/bin/phpunit --colors=always --testdox
            tearDownCmd: |
              docker logs chrome > ./logs/chrome.docker.log

          - name: Selenium2
            driverRepoUrl: https://github.com/minkphp/MinkSelenium2Driver.git
            php: 7.2
            setUpCmd: |
              docker run --detach --quiet --net host --volume /dev/shm:/dev/shm --shm-size 2g --volume ./vendor/mink/driver-testsuite/web-fixtures:/fixtures \
                         --name selenium selenium/standalone-firefox:2.53.1
              curl --retry 5 --retry-all-errors --retry-delay 1 --max-time 10 --head -X GET http://localhost:4444/wd/hub/status
            testCmd: |
              export WEB_FIXTURES_BROWSER=firefox
              export DRIVER_MACHINE_BASE_PATH=/fixtures/
              ./vendor/bin/phpunit --colors=always --testdox
            tearDownCmd: |
              docker logs selenium > ./logs/selenium.docker.log

          - name: WebDriver-Classic
            driverRepoUrl: https://github.com/minkphp/webdriver-classic-driver.git
            php: 7.4
            setUpCmd: |
              export SELENIUM_IMAGE=selenium/standalone-firefox:4
              docker compose up --wait --quiet-pull
              curl --retry 5 --retry-all-errors --retry-delay 1 --max-time 10 --head -X GET http://localhost:4444/wd/hub/status
            testCmd: |
              export WEB_FIXTURES_BROWSER=firefox
              export DRIVER_MACHINE_BASE_PATH=/fixtures/
              ./vendor/bin/phpunit --colors=always --testdox

    steps:
      - name: Set up workspace for driver repo
        run: git clone ${{ matrix.driverRepoUrl }} .

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install driver dependencies
        run: composer install --no-interaction --ansi --no-progress

        # This is instead of `composer require "mink/driver-testsuite:dev-master#${{ github.sha }}"`, which works with forks
      - name: Set up driver test suite as composer dependency
        uses: actions/checkout@v4
        with:
          path: ./vendor/mink/driver-testsuite

      - name: Set up
        run: |
          mkdir ./logs
          ./vendor/bin/mink-test-server &> ./logs/mink-test-server.log &
          eval "${{ matrix.setUpCmd }}"
          curl --retry 5 --retry-all-errors --retry-delay 1 --max-time 10 --head -X GET http://localhost:8002/

      - name: Run tests
        run: eval "${{ matrix.testCmd }}"

      - name: Tear down
        run: |
          eval "${{ matrix.tearDownCmd }}"

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.name }}-logs
          path: ./logs
